/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118469-g75ade2dd49-20250214"
#endif /* AVUTIL_FFVERSION_H */
